#!/usr/bin/python3
from math import sqrt
from sys import argv


def fact1(num):

    sqrt_num = int(sqrt(abs(num)))

    for i in range(2, 10000):
        if num % i == 0:
            print(f"{num}={num//i}*{i}")
            return 1
    return 0


def fact2(num):

    i = int(sqrt(abs(num)))
    while i >= 10000:
        if num % i == 0:
            print(f"{num}={num//i}*{i}")
            return
        i -= 1
    print(f"{num}={num}*{1}")


def RSA():

    if len(argv) > 1:
        input_file = argv[1]
        try:
            with open(input_file, "r") as f:
                factors = []
                line = f.readline()
                while line:
                    if line == "\n":
                        break
                    if fact1(int(line)) == 0:
                        fact2(int(line))
                    line = f.readline()
        except FileNotFoundError:
            print(f"Error: Can't open file {argv[1]}")
    else:
        print("Usage: factors <file>")


RSA()
